Raise an error for invalid scatter data
automl/SMAC3 pull request #1018
Opened 2023-05-26 21:17 UTC by nabenabe0928

When `data_to_scatter={}`, it causes an error in Dask, so I fixed this error.

2023-06-01 09:36 UTC, alexandertornede commented
Thanks for this PR, @nabenabe0928! Overall, it looks good to me. Could you please add this to the CHANGELOG.md as well? :)  

Let's see whether @benjamc has another opinion as she is the expert on the DASK runner.

2023-06-01 13:11 UTC, benjamc requested changes
Looks good, can you update the changelog as Alex suggested?:)

2023-06-02 07:44 UTC, nabenabe0928 commented
@benjamc @alexandertornede 
Thanks for the review:)
I updated the CHANGELOG.md!

2023-06-06 12:35 UTC, benjamc approved these changes

2023-06-06 12:35 UTC, benjamc commented
Thank you, @nabenabe0928! 🌞

2023-06-06 12:45 UTC, merged