Adding in CPU time to wherever time is defined as variable "cpu_time"
automl/SMAC3 pull request #1173
Opened 2024-11-26 14:08 UTC by thijssnelleman

Changed the TrialValue to hold CPU time and have SMBO use this value to calculate its budgets

- Same behaviour as the original 'time' variable, except in its calculation tries to estimate CPU time with process_time instead.
- Added in to TrialValue object, RunHistory and SMBO so it can be recorded and correctly calculate the remaining CPU budget

Pytest are passing (on my machine)

2024-11-27 14:51 UTC, benjamc requested changes
is there any way to test the new cpu return? if yes, please add a little test

otherwise, codewise the PR LGTM, it only needs a bit more documentation.
You can basically copy/paste the description for cpu_time everywhere.

2024-11-27 14:51 UTC, benjamc commented on CHANGELOG.md
> +- Separated Wallclock time measurements from CPU time measurements and storing them under new 'cpu_time' variable (#????)
update PR number

2024-11-27 14:51 UTC, benjamc commented on smac/main/smbo.py
> +        """Returns how much cputime the target function spend so far."""
describe that CPU time generally means time spent on the hardware and not just CPU (whether its CPU, TPU, GPU or whatever)

2024-11-27 14:51 UTC, benjamc commented on smac/runhistory/dataclasses.py
> +    cpu_time : float, defaults to 0.0
describe CPU time (what it means and why/ in what way it differs from time)

2024-11-27 14:51 UTC, benjamc commented on smac/runhistory/runhistory.py
> +        cpu_time : float
Same here, add a little more info

2024-11-27 14:51 UTC, benjamc commented on smac/runhistory/runhistory.py
> +        # NOTE: These hardcoded indices can easily lead to trouble
agreed

2024-11-29 10:37 UTC, thijssnelleman commented on smac/runhistory/runhistory.py
> +        # NOTE: These hardcoded indices can easily lead to trouble
https://github.com/automl/SMAC3/issues/1174

2024-11-29 10:49 UTC, thijssnelleman commented
Added in CPU time tests in target function runner tests

2024-11-29 12:07 UTC, benjamc approved these changes

2024-11-29 12:22 UTC, merged