Examples update
automl/SMAC3 pull request #742
Opened 2021-07-16 16:27 UTC by eddiebergman

# Features
* Makes the quickstart guide runnable by [sphinx-gallry](https://sphinx-gallery.github.io/stable/index.html).
* Makes examples also runnable by sphinx-gallery.

# Major changes
* `quickstart.rst` was converted to a `quickstart_example.py` to enable sphinx-gallery.
* Folder structure change so that the ToC in the docs seperate quickstart and examples.
* Examples renamed from `*.py` to `*_example.py`, unless file name was `*_func.py`, in which case it was unchanged.

# Does not
* Does not improve the code or text of the examples except for minor changes in `quickstart_example.py`

# Issues
* 6 examples fail to run for unknown import errors, the log of which is given below 
<details>
<summary>`make doc`</summary>

```
make -C doc html
make[1]: Entering directory '/home/skantify/code/SMAC3/doc'
sphinx-build -b html -d build/doctrees   . build/html
Running Sphinx v4.1.1
loading pickled environment... done
[autosummary] generating autosummary for: api.rst, basic_usage.rst, contact.rst, examples/BOHB4HPO_mlp_example.rst, examples/BOHB4HPO_sgd_instances_example.rst, examples/SMAC4BO_rosenbrock_example.rst, examples/SMAC4HPO_acq_rosenbrock_example.rst, examples/SMAC4HPO_gradientboosting_example.rst, examples/SMAC4HPO_rf_example.rst, examples/SMAC4HPO_rosenbrock_example.rst, ..., options.rst, psmac.rst, quickstart/index.rst, quickstart/quickstart_example.rst, quickstart/sg_execution_times.rst, scenario_options.rst, smac_options.rst, tae.rst, usage_recomendation.rst, validation.rst
generating gallery...
WARNING: /home/skantify/code/SMAC3/examples/general/fmin_rosenbrock_example.py failed to execute correctly: Traceback (most recent call last):                                                
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/skantify/code/SMAC3/examples/general/fmin_rosenbrock_example.py", line 9, in <module>
    from smac.facade.func_facade import fmin_smac
ModuleNotFoundError: No module named 'smac.facade'

WARNING: /home/skantify/code/SMAC3/examples/general/fmin_rosenbrock_parallel_example.py failed to execute correctly: Traceback (most recent call last):                                       
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/skantify/code/SMAC3/examples/general/fmin_rosenbrock_parallel_example.py", line 12, in <module>
    from smac.intensification.simple_intensifier import SimpleIntensifier
ModuleNotFoundError: No module named 'smac.intensification.simple_intensifier'

WARNING: /home/skantify/code/SMAC3/examples/general/SMAC4BO_rosenbrock_example.py failed to execute correctly: Traceback (most recent call last):                                             
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/skantify/code/SMAC3/examples/general/SMAC4BO_rosenbrock_example.py", line 14, in <module>
    from smac.facade.smac_bo_facade import SMAC4BO
ModuleNotFoundError: No module named 'smac.facade.smac_bo_facade'

WARNING: /home/skantify/code/SMAC3/examples/general/hyperband_mlp_example.py failed to execute correctly: Traceback (most recent call last):                                                  
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/skantify/code/SMAC3/examples/general/hyperband_mlp_example.py", line 21, in <module>
    from smac.facade.hyperband_facade import HB4AC
ModuleNotFoundError: No module named 'smac.facade.hyperband_facade'

WARNING: /home/skantify/code/SMAC3/examples/general/BOHB4HPO_sgd_instances_example.py failed to execute correctly: Traceback (most recent call last):                                         
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/skantify/code/SMAC3/.venv/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/skantify/code/SMAC3/examples/general/BOHB4HPO_sgd_instances_example.py", line 29, in <module>
    from smac.facade.smac_bohb_facade import BOHB4HPO
ModuleNotFoundError: No module named 'smac.facade.smac_bohb_facade'

generating gallery for examples... [100%] BOHB4HPO_mlp_example.py                                                                                                                             
generating gallery for quickstart... [100%] quickstart_example.py                                                                                                                             
computation time summary:
    - ../examples/general/BOHB4HPO_sgd_instances_example.py:      0.03 sec   0.0 MB
    - ../examples/general/hyperband_mlp_example.py:               0.00 sec   0.0 MB
    - ../examples/general/SMAC4BO_rosenbrock_example.py:          0.00 sec   0.0 MB
    - ../examples/general/fmin_rosenbrock_example.py:             0.00 sec   0.0 MB
    - ../examples/general/fmin_rosenbrock_parallel_example.py:    0.00 sec   0.0 MB
    - ../examples/general/BOHB4HPO_mlp_example.py:                0.00 sec   0.0 MB
    - ../examples/general/SMAC4HPO_acq_rosenbrock_example.py:     0.00 sec   0.0 MB
    - ../examples/general/SMAC4HPO_gradientboosting_example.py:   0.00 sec   0.0 MB
    - ../examples/general/SMAC4HPO_rf_example.py:                 0.00 sec   0.0 MB
    - ../examples/general/SMAC4HPO_rosenbrock_example.py:         0.00 sec   0.0 MB
    - ../examples/general/SMAC4HPO_svm_example.py:                0.00 sec   0.0 MB
    - ../examples/general/parallel_sh_mlp_example.py:             0.00 sec   0.0 MB
    - ../examples/quickstart/quickstart_example.py:               0.00 sec   0.0 MB
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 0 added, 9 changed, 0 removed
reading sources... [100%] smac_options                                                                                                                                                        
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.callbacks'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.configspace'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.epm'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.facade'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.initial_design'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.intensification'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.optimizer'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNING: toctree contains reference to nonexisting document 'apidoc/smac.runhistory'
/home/skantify/code/SMAC3/doc/api.rst:9: WARNI [...]

2021-07-20 07:37 UTC, renesass commented
Gonna have a look into that later

2021-07-20 07:38 UTC, dengdifan commented
1. We renamed BOHB4HPO to SMAC4MF in a previous PR #738, could you please do the same to all  BOHB related files?
2. We deleted the example for RF in #722, maybe you could do the same?

2021-07-20 08:10 UTC, eddiebergman commented
I will get around to it in the second half of the day hopefully, do you guys have a major release for the paper planned soon?

2021-07-21 06:45 UTC, renesass commented
actually, I don't like how the examples are sorted. Can we maybe create subfolders? E.g. 
SMAC4HPO_rf_example.py -> SMAC4HPO/rf.py
hyperband_mlp_example.py -> HB/mlp.py

2021-07-21 06:57 UTC, renesass commented
the whole spear_qcp seems way to complex to me. We should consider moving it to the general examples.

2021-07-21 07:19 UTC, benjamc commented
> 
> 
> actually, I don't like how the examples are sorted. Can we maybe create subfolders? E.g.
> SMAC4HPO_rf_example.py -> SMAC4HPO/rf.py
> hyperband_mlp_example.py -> HB/mlp.py

Good idea. Would look cleaner.

2021-07-21 07:21 UTC, benjamc commented
> 
> 
> the whole spear_qcp seems way to complex to me. Way too much files, too. Are they even needed and called? We should consider moving it to the general examples.

Moving it to general sounds good, and it is good to have this more complex example. Maybe we could add a really small readme saying that we want to optimize spear qcp and what it is (I didn't know:D)  and with which script/file to start.

2021-07-21 07:31 UTC, renesass requested changes

2021-07-21 07:48 UTC, eddiebergman commented on .gitignore
> +examples/general/smac3-output_*
Good idea

2021-07-21 07:53 UTC, eddiebergman commented on examples/general/parallel_sh_mlp_example.py
> +sys.path.append(os.getcwd())
I left the original as a comment along with the link to indicate why. Anyone viewing the example might consider `os.cwd()` a bit odd to see. 

When Sphinx-Gallery runs an example, the variable `__file__` is undefined. It runs the file from the file's source directory so `os.cwd()` accomplishes the same task and is the recommended solution by them. 

https://sphinx-gallery.github.io/stable/faq.html#why-is-file-not-defined-what-can-i-use

2021-07-21 08:59 UTC, eddiebergman commented
> actually, I don't like how the examples are sorted. Can we maybe create subfolders? E.g.
> SMAC4HPO_rf_example.py -> SMAC4HPO/rf.py
> hyperband_mlp_example.py -> HB/mlp.py

I began moving them to their own subfolders as I like the idea too but the issue is that a lot of examples rely on `mlp_from_cfg_func.py`.

The line `from mlp_from_cfg_func import mlp_from_cfg` that exists in most of them only work if the importing file and `mlp_from_cfg_func.py` exist in the same directory. It is possible to just add more to the path but it obscures the examples a bit in my opinion. In general, I'm not really a fan of multi-file examples as it introduces more areas to go wrong.

For now, I will try to give the examples a module structure, introducing `__init__.py` and see if I can get relative imports working.
i.e.
```
/quickstart/
/general/
---- /subfolder1/
---- ---- __init__.py
---- ---- example1.py
---- /subfolder2/
---- ---- __init__.py
---- ---- example2.py
---- __init__.py
---- mlp_from_cfg_func.py
```
And then in the examples
```python
# example1.py
from ..mlp_from_cfg_func import mlp_from_cfg
```

The alternative as suggested is to add to the parent path in each example
```python
sys.path.append(os.getcwd()) # Add directory the example is in
sys.path.append(os.path.join('..', os.getcwd()) # Add parent directory
```
This will however break if any folder restructuring is done and won't work if a user downloads the examples and runs the example themselves outside the directory.
```sh
$ cwd
> ..../general
$ python subfolder1/example1.py
> Something along the lines of `mlp_from_cfg_func` can't be imported
```

2021-07-21 09:30 UTC, eddiebergman commented
Scratch that, the module method didn't work. For now a simple solution is just add the parent directory and account for whether it is run by a user or by sphinx gallery (in which case `__file__` does not exist.

```python
# https://sphinx-gallery.github.io/stable/faq.html#why-is-file-not-defined-what-can-i-use
cwd = os.path.dirname(__file__) if __file__ else os.getcwd()
sys.path.append(os.path.join(cwd, os.pardir))  # mlp_from_cfg_func lives one dir up
from mlp_from_cfg_func import mlp_from_cfg  # noqa: E402
```

2021-07-21 09:37 UTC, eddiebergman commented
Actually I noticed [SMAC4MF_mlp.py](https://github.com/automl/SMAC3/blob/development/examples/SMAC4MF_mlp.py) has the `mlp_from_cfg` function directly in the example. This removes the external file dependancy and I think this is likely the better option at the cost of making the example longer.

2021-07-21 14:04 UTC, eddiebergman commented
There are still 6 failing examples but I can not solve them, they are all imports in only 'some' examples.

2021-07-22 07:33 UTC, eddiebergman commented
There should also probably be tests for checking if all examples execute correctly for the future, I'm busy until next wednesday and I'm not sure when this PR is required for the papers. I can raise an issue for it if you like?

2021-07-22 10:10 UTC, eddiebergman commented
Examples with `sphinx-gallery` are only run successfully with `python 3.9`, can't identify why it would matter

2021-08-04 12:03 UTC, dengdifan commented
Under Manual -> Basic Usage -> Usage in python, the link to SVM-example, ExecuteTAFuncDict and ExexuteTAFuncArray are broken.
Under Manual -> Options and file formats, link to SVM-example and SPEAR example also broken 
Under Manual ->Target Algorithm Evaluator, almost all link break.
Same for Manual -> Validation

2021-08-04 15:31 UTC, eddiebergman commented
As updated in the PR main comment, the linkcheck functionality gives a lot of false negatives. Through manual checking they all seem to work as intended. I would suggest in the future, once this release if published and over, switching how referencing is done to instead use the internal 'anchors' in each `rst` file rather than reference `html` files that will be generated.

I wrote a small example here for any future work on fixing up documentation or the false negative errors generated by `linkcheck` with sphinx
```bash
$ cd doc; make linkcheck
```

### Examples for link changing
```rst
# file_one.rst

.. _my_anchor:

.. _explicit_title_anchor:
Title
=====
```

```rst
# file_two.rst

Here I want to :ref:`another anchor in another file <my_anchor>` which
will work as long as `my_anchor` is present in any file during the build.

... as opposed to how it's `currently done <file_two.html#my_anchor>`_
which will fail if any reorganization of the docs are done such as moving `file_one` to `../file_one`.

Also using the title such as `file_one.html#Title` will fail if someone want's to change the Title displayed yet
this :ref:`one <explicit_title_anchor>` will not
```

2021-08-05 11:24 UTC, renesass approved these changes

2021-08-05 11:30 UTC, merged