Add a workaround to be able pass a dataset via dask.scatter
automl/SMAC3 pull request #993
Opened 2023-05-02 14:18 UTC by nabenabe0928

# Background

When we run SMAC using a tabular benchmark or a surrogate benchmark, SMAC incurs a significant slowdown due to the (de-)serialization problem.

The problem here is that when a given target function refers to such a benchmark, the target function must be serialized to be passed to each process and be deserialized when each process uses it.
However, (de-)serialization is unnecessary because both tabular and surrogate benchmarks are static.
For this reason, we would like to use dask.scatter to be able to keep such a benchmark in memory.

This PR gives the feature to do so.

**NOTE**: This PR will be merged to the `main` branch, but we probably do not want to do it, so please take care of the branch to be merged.

2023-05-02 19:31 UTC, eddiebergman reviewed
Seems good but likely linters will shout at you for some pointed out reasons.

This more generally seems like a method to pass your own kwargs to a target function, i.e.

```python
def my_target_function(..., *, my_extra_object: str):
    ...
    
smac.optimize(
    my_target_function,
    shared_data={"my_extra_object": "hello_world"}
)
```

The problem here is that I could easily use the functionality for this purpose, without knowing that under the hood, this is issuing a `dask.scatter`. I don't really know the implications of `dask.scatter` so that may not be an issue though.

Seeing as this is a relatively "advanced" feature, it might make sense to make the argument more obscure on purpose? For example,
`smac.optimize(dask_scatter={"x": y}). It's immediately clear it's dask specific and what functionality it invokes. For anyone unaware, it would encourage them to read the docstrings and force them to understand the choice they are making.

One example is it would also help people understand the case where it's not a `DaskParallelRunner` and why suddenly their `my_extra_object = "hello"` never makes it to their target function?

All that being said, perhaps there should be some extra arguments along the lines of what you have done but are just passed through `client.submit` and not necessarily using `dask.scatter`

2023-05-02 19:31 UTC, eddiebergman commented on smac/facade/abstract_facade.py
> +    def optimize(self, shared_data=None) -> Configuration | list[Configuration]:
Can we add a proper type to it? I'm not sure if it's of a special type or just a `dict[str, Any]`? A brief comment about the argument would also be helpful :)

```suggestion
    def optimize(self, shared_data: dict[str, Any] | None = None) -> Configuration | list[Configuration]:
```

2023-05-02 19:31 UTC, eddiebergman commented on smac/main/smbo.py
> +    def optimize(self, shared_data=None) -> Configuration | list[Configuration]:
Same here regarding the typing and docstring

2023-05-02 19:31 UTC, eddiebergman commented on smac/runner/abstract_runner.py
> +    def run_wrapper(self, trial_info: TrialInfo, **shared_dict) -> tuple[TrialInfo, TrialValue]:
```suggestion
    def run_wrapper(self, trial_info: TrialInfo, **shared_dict: Any) -> tuple[TrialInfo, TrialValue]:
```

2023-05-02 19:31 UTC, eddiebergman commented on smac/runner/dask_runner.py
> +        **shared_dict,
```suggestion
        **shared_dict: Any,
```

2023-05-02 19:31 UTC, eddiebergman commented on smac/runner/target_function_runner.py
> +        **shared_dict,
```suggestion
        **shared_dict: Any,
```

2023-05-03 13:40 UTC, eddiebergman requested changes

2023-05-03 13:40 UTC, eddiebergman commented on smac/facade/abstract_facade.py
> +        dask_data_to_scatter: dict[str, Any] | None
Just a correct to the param name :)

2023-05-03 13:40 UTC, eddiebergman commented on smac/main/smbo.py
> +
The error you're getting from the checks are from here, this suggestion should fix it.

```python
elif any(dask_data_to_scatter):
    ...
```

2023-05-04 12:18 UTC, eddiebergman approved these changes

2023-05-04 12:20 UTC, eddiebergman commented
Added @benjamc as a reviewer since I do not have god-mode to accept changes and 2 reviewers are required. I thought you might be the most familiar? If not, please recommend someone else who knows dask :))

2023-05-16 13:07 UTC, benjamc commented
Thank you for the PR!
Could you also update the `CHANGELOG.md`?

2023-05-16 14:09 UTC, nabenabe0928 commented on smac/facade/abstract_facade.py
> +        retries: int = 1000,
Thanks for raising this point, I do not know why it sneaked into this PR, but this is a heuristic for my own experiment, so I will get it back.

2023-05-16 14:15 UTC, nabenabe0928 commented
> Thank you for the PR! Could you also update the `CHANGELOG.md`?

Done!

2023-05-16 14:15 UTC, benjamc commented on smac/facade/abstract_facade.py
> +        retries: int = 1000,
Thanks!

2023-05-16 14:16 UTC, benjamc approved these changes

2023-05-16 14:21 UTC, benjamc approved these changes

2023-05-16 14:34 UTC, merged